// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd1k95a7NKrXjoP6IIcEn6VRFWdmYpn4M',
    appId: '1:876854854042:web:baf5fbe366d5d00412ba23',
    messagingSenderId: '876854854042',
    projectId: 'carrent-91634',
    authDomain: 'carrent-91634.firebaseapp.com',
    storageBucket: 'carrent-91634.appspot.com',
    measurementId: 'G-SF9KDCY1C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1EVKIXU8zfJRA_WvBJQs2v7nV7lVsk6A',
    appId: '1:876854854042:android:baf29f42b8257de512ba23',
    messagingSenderId: '876854854042',
    projectId: 'carrent-91634',
    storageBucket: 'carrent-91634.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYJI1G02bPjmStNx0iKmmF8iIkP6QdXz4',
    appId: '1:876854854042:ios:784b670f7308685312ba23',
    messagingSenderId: '876854854042',
    projectId: 'carrent-91634',
    storageBucket: 'carrent-91634.appspot.com',
    iosBundleId: 'com.example.carrent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYJI1G02bPjmStNx0iKmmF8iIkP6QdXz4',
    appId: '1:876854854042:ios:784b670f7308685312ba23',
    messagingSenderId: '876854854042',
    projectId: 'carrent-91634',
    storageBucket: 'carrent-91634.appspot.com',
    iosBundleId: 'com.example.carrent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd1k95a7NKrXjoP6IIcEn6VRFWdmYpn4M',
    appId: '1:876854854042:web:5adc3558f0f53cf312ba23',
    messagingSenderId: '876854854042',
    projectId: 'carrent-91634',
    authDomain: 'carrent-91634.firebaseapp.com',
    storageBucket: 'carrent-91634.appspot.com',
    measurementId: 'G-GTMXWHMWTB',
  );
}
